version: '3.8'

services:
  web:
    container_name: web
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    restart: unless-stopped
  db:
    container_name: db
    #image: postgres:13-alpine
    #image: kartoza/postgis:14-3.2
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      #- ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    #ports:
    #  - "5436:5432"
    restart: unless-stopped
volumes:
  postgres_data: