"""empty message

Revision ID: 989b839a92b5
Revises: 
Create Date: 2022-06-28 22:15:07.167659

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '989b839a92b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geo', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('fp', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('cities')
    # ### end Alembic commands ###
